# Этот файлик = github-action. Он будет запускаться автоматом при пуше, и выполнять build, чтобы автоматически проверять, что код без ошибок
name: maven-build
on:
  push:
    branches: [ "main" ]                                              # Action будет выполняться при пуше в ветку main
  pull_request:
    branches: [ "main" ]                                              # Action будет выполняться при MR в ветку main

jobs:
  checkstyle:
    runs-on: ubuntu-20.04
    steps:
#      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml')}}
          restore-keys: |
            maven-
      - run: mvn clean install
